"""one live session per course

Revision ID: 68112610ff18
Revises: 75b8df57d7e9
Create Date: 2026-07-04 22:46:44.010454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68112610ff18'
down_revision = '75b8df57d7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index('uq_one_live_session_per_course', ['course_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL AND NOT voided'), sqlite_where=sa.text('ended_at IS NULL AND NOT voided'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index('uq_one_live_session_per_course', postgresql_where=sa.text('ended_at IS NULL AND NOT voided'), sqlite_where=sa.text('ended_at IS NULL AND NOT voided'))

    # ### end Alembic commands ###
